name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pandas
  - numpy
  - matplotlib.pylot
  - bokeh.colors
  - bokeh.palettes
  - bokeh.transform
  - math
  - json
  - pprint
